Update tests-01-main.yml

diff --git a/.github/workflows/tests-01-main.yml b/.github/workflows/tests-01-main.yml
--- a/.github/workflows/tests-01-main.yml
+++ b/.github/workflows/tests-01-main.yml
@@ -39,16 +39,20 @@ jobs:
           chmod a+x ./deb-get
           export DEBIAN_FRONTEND=noninteractive
           set -x
-          APPS="$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep "^01-main/packages/" | sed "s|^01-main/packages/||")"
-          SUPPORTED="$(./deb-get list --raw)"
+          #PRS=${{ github.event.pull_request.base.sha ||  github.head_ref }}
+          APPS="$(git diff --name-only --diff-filter=ACMRT  ${{ github.event.pull_request.base.sha || github.event.push.before}} ${{ github.sha }} | grep "^01-main/packages/" | sed "s|^01-main/packages/||")"
           for APP in ${APPS}; do
-            if echo "${SUPPORTED}" | grep -q -m 1 "^${APP}$"; then
-              ./deb-get install "${APP}"
-              if ./deb-get show "${APP}" | grep -q "Installed:	No"; then
-                echo "Failed to detect ${APP} as installed" >&2
-                exit 1
-              else
-                ./deb-get purge "${APP}"
+            if grep -q -m 1 "^${APP}$" ./01-main/manifest; then
+              if ./deb-get install "${APP}" 2>&1 | grep -e 'ERROR! .* is not supported on ' ; then
+                UNSUPPORTED=Marked
+              fi
+              if [ ! ${UNSUPPORTED}==Marked ]; then
+                if ./deb-get show "${APP}" | grep -q "Installed:	No"; then
+                  echo "Failed to detect ${APP} as installed" >&2
+                  exit 1
+                else
+                  ./deb-get purge "${APP}"
+                fi
               fi
             fi
           done
